# Generated by Django 5.0.2 on 2024-03-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='about',
            field=models.CharField(default='MBA candidate transitioning from successful legal career to business and management. Established as diligent legal professional with extensive background and track record. Adept in drafting, research, and advocacy. Proficient in advising, negotiating, due diligence. Dedicated to achieving optimal outcomes for clients and organizations.', max_length=500),
        ),
    ]
