# Generated by Django 5.0.2 on 2024-03-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='AppointmentModel',
        ),
    ]
