# Generated by Django 5.0.2 on 2024-03-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_publications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentModel',
        ),
    ]
