# Generated by Django 5.0.2 on 2024-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_appointmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
