# Generated by Django 5.0.2 on 2024-03-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_affliations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affliations',
            new_name='Affiliations',
        ),
    ]
