# Generated by Django 5.0.2 on 2024-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_affliations_affiliations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
