# Generated by Django 5.0.2 on 2024-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_publications_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='title',
        ),
        migrations.AlterField(
            model_name='publications',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
