# Generated by Django 5.0.2 on 2024-03-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_publications_title_alter_publications_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='field2',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
